# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'DZ9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DZ9
  pod 'Alamofire'

end
